# Generated by Django 6.0.4 on 2026-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO/Founder'), ('HR', 'HR Manager'), ('Dept Head', 'Department Head'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
