# Generated by Django 6.0.4 on 2026-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_qm_id_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
