# Generated by Django 6.0.4 on 2026-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Open', 'Open'), ('Not Interested', 'Not Interested'), ('Closed', 'Closed (Won)')], default='Not Started', max_length=50),
        ),
    ]
