# Generated by Django 6.0.4 on 2026-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_financialrecord_project_invoice_lineitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('HR', 'Human Resources'), ('Dept Head', 'Department Head'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
