# Generated by Django 6.0.4 on 2026-04-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_invoice_discount_invoice_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Deployed', 'Deployed')], default='Not Started', max_length=50),
        ),
    ]
