# Generated by Django 6.0.4 on 2026-04-19 13:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_last_activity_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=api.models.generate_invoice_number, editable=False, max_length=50, unique=True),
        ),
    ]
