# Generated by Django 6.0.4 on 2026-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='google_meet_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
