# Generated by Django 6.0.4 on 2026-04-20 09:35

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    User = apps.get_model('api', 'User')
    for row in User.objects.all():
        while True:
            new_id = f"QM-{uuid.uuid4().hex[:6].upper()}"
            if not User.objects.filter(qm_id=new_id).exists():
                row.qm_id = new_id
                break
        row.save(update_fields=['qm_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_meeting_agenda_meeting_google_meet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='qm_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='qm_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
