version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: qmexai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn erp_core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgrespassword@db:5432/qmexai_db
      - DEBUG=True
      - SECRET_KEY=local-dev-key
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
